version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-rappi_lockers}
    ports:
      - '5432:5432' # Host:Container
    volumes:
      - db_data:/var/lib/postgresql/data # Persist database data

  backend:
    build:
      context: . # Build context is the root directory
      dockerfile: backend/Dockerfile # Path to the backend's Dockerfile
    restart: always
    environment:
      PORT: 5000
      DB_HOST: db # This connects to the 'db' service defined above
      DB_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-rappi_lockers}
    ports:
      - '5000:5000' # Host:Container
    depends_on:
      - db # Ensures db service starts before backend

volumes:
  db_data: # Define the named volume for database persistence
